// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeRnsiX23H5M_FUyep2dbEPUXjzFvm2Cg',
    appId: '1:422469730222:web:a464bc7f4b4e76e5bb523f',
    messagingSenderId: '422469730222',
    projectId: 'godzilla-1b569',
    authDomain: 'godzilla-1b569.firebaseapp.com',
    storageBucket: 'godzilla-1b569.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsqFq1tRB6AlsEldUPYrbj07qEpNGI2ZY',
    appId: '1:422469730222:android:84c58c3aad0d1301bb523f',
    messagingSenderId: '422469730222',
    projectId: 'godzilla-1b569',
    storageBucket: 'godzilla-1b569.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv2dUJAxn7v89dzHxnuhXgseQwgT9EfRE',
    appId: '1:422469730222:ios:87d3c102c3fa8fdfbb523f',
    messagingSenderId: '422469730222',
    projectId: 'godzilla-1b569',
    storageBucket: 'godzilla-1b569.firebasestorage.app',
    iosBundleId: 'com.piyush.godzilla',
  );
}
