// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'data/models/message_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 6788101922495677752),
    name: 'ChatMessage',
    lastPropertyId: const obx_int.IdUid(6, 4534217806517932230),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 1160663197243245420),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5280660217030410060),
        name: 'senderId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 451372951109246997),
        name: 'recipientId',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3415472865460311635),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 301199224824158172),
        name: 'timestamp',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4534217806517932230),
        name: 'isRead',
        type: 1,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 6788101922495677752),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ChatMessage: obx_int.EntityDefinition<ChatMessage>(
      model: _entities[0],
      toOneRelations: (ChatMessage object) => [],
      toManyRelations: (ChatMessage object) => {},
      getId: (ChatMessage object) => object.id,
      setId: (ChatMessage object, int id) {
        object.id = id;
      },
      objectToFB: (ChatMessage object, fb.Builder fbb) {
        final senderIdOffset = fbb.writeString(object.senderId);
        final recipientIdOffset = fbb.writeString(object.recipientId);
        final contentOffset = fbb.writeString(object.content);
        final timestampOffset = fbb.writeString(object.timestamp);
        fbb.startTable(7);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, senderIdOffset);
        fbb.addOffset(2, recipientIdOffset);
        fbb.addOffset(3, contentOffset);
        fbb.addOffset(4, timestampOffset);
        fbb.addBool(5, object.isRead);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final senderIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final recipientIdParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 8, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final timestampParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 12, '');
        final isReadParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final object = ChatMessage(
          id: idParam,
          senderId: senderIdParam,
          recipientId: recipientIdParam,
          content: contentParam,
          timestamp: timestampParam,
          isRead: isReadParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ChatMessage] entity fields to define ObjectBox queries.
class ChatMessage_ {
  /// See [ChatMessage.id].
  static final id = obx.QueryIntegerProperty<ChatMessage>(
    _entities[0].properties[0],
  );

  /// See [ChatMessage.senderId].
  static final senderId = obx.QueryStringProperty<ChatMessage>(
    _entities[0].properties[1],
  );

  /// See [ChatMessage.recipientId].
  static final recipientId = obx.QueryStringProperty<ChatMessage>(
    _entities[0].properties[2],
  );

  /// See [ChatMessage.content].
  static final content = obx.QueryStringProperty<ChatMessage>(
    _entities[0].properties[3],
  );

  /// See [ChatMessage.timestamp].
  static final timestamp = obx.QueryStringProperty<ChatMessage>(
    _entities[0].properties[4],
  );

  /// See [ChatMessage.isRead].
  static final isRead = obx.QueryBooleanProperty<ChatMessage>(
    _entities[0].properties[5],
  );
}
